In [ ]:
#here in this diabetes datasets i tried to predict whether the person has diabetes or not based on the features given.
#two columns age and bmi has null value and tried to impute those with mean of all their respective datas.

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn import svm

diabetes_ds = pd.read_csv("/content/diabetes.csv")

In [ ]:
diabetes_ds.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50.0,1
1,1,85,66,29,0,26.6,0.351,31.0,0
2,8,183,64,0,0,23.3,0.672,32.0,1
3,1,89,66,23,94,28.1,0.167,21.0,0
4,0,137,40,35,168,43.1,2.288,33.0,1

In [ ]:
diabetes_ds.shape

(768, 9)

In [ ]:
diabetes_ds.sample(frac = 1, random_state = 42)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
668,6,98,58,33,190,34.0,0.430,43.0,0
324,2,112,75,32,0,35.7,0.148,21.0,0
624,2,108,64,0,0,30.8,0.158,21.0,0
690,8,107,80,0,0,24.6,0.856,34.0,0
473,7,136,90,0,0,29.9,0.210,50.0,0
...,...,...,...,...,...,...,...,...,...
71,5,139,64,35,140,28.6,0.411,26.0,0
106,1,96,122,0,0,22.4,0.207,27.0,0
270,10,101,86,37,0,45.6,1.136,38.0,1
435,0,141,0,0,0,42.4,0.205,29.0,1
102,0,125,96,0,0,22.5,0.262,21.0,0

In [ ]:
# X = diabetes_ds.drop(columns = 'Outcome', axis = 1)
# y = diabetes_ds['Outcome']
diabetes_ds.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.340081,0.429734,31.193939
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.153184,0.550500,36.893939

In [ ]:
X = diabetes_ds.drop(columns = 'Outcome', axis = 1)
y = diabetes_ds['Outcome']

In [ ]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 42,stratify = y)

In [ ]:
# standardize the data to a particular level(between 0 and 1)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# imputing missing values
imputer = SimpleImputer(strategy='mean')
cols_to_impute = ['Age', 'BMI']
X_train_scaled = pd.DataFrame(imputer.fit_transform(X_train_scaled), columns=X_train.columns)
X_test_scaled = pd.DataFrame(imputer.transform(X_test_scaled), columns=X_test.columns)

In [ ]:
#fitting the models
clf = svm.SVC(kernel='linear')
clf.fit(X_train_scaled, y_train)
y_pred = clf.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7077922077922078

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100)
clf.fit(X_train_scaled,y_train)
y_pred = clf.predict(X_test_scaled)
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7467532467532467